FinanceSystem/Models/UserInformation.cs
namespace FinanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Web;

    [Table("UserInformation")]
    public partial class UserInformation
    {
        [Key]
        public string UserId { get; set; }

        [StringLength(50)]
        public string FirstName { get; set; }

        [StringLength(50)]
        public string LastName { get; set; }

        [Column(TypeName = "date")]
        public DateTime? BirthDate { get; set; }

        public bool? Gender { get; set; }

        [StringLength(100)]
        public string Image { get; set; }
        public HttpPostedFileBase ImageFile;

        public virtual AspNetUser AspNetUser { get; set; }
    }
}

FinanceSystem/Areas/Admin/Controllers/UserInformationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FinanceSystem.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;

namespace FinanceSystem.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]

    public class UserInformationsController : Controller
    {

        private FinanceSystemDBContext db = new FinanceSystemDBContext();
        // GET: Admin/UserInformations
        public ActionResult Index()
        {        
            
            return View(db.AspNetUsers.ToList());
            
        }

        // GET: Admin/UserInformations/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
               return View("~/Views/Shared/Error.cshtml");
            }
            var transaction = db.Transactions.Where(x => x.Wallet.UserId == id).ToList();
            var wallet = db.Wallets.Where(x => x.UserId == id).ToList();
            if (wallet.Count == 0)
            {
                ViewBag.Total = 0;
			}
            else 
            {
				ViewBag.Total = db.Wallets.Where(x => x.UserId == id).Sum(x => x.AccountBalance.Value);
			}
           
            ViewBag.Image = db.UserInformations.FirstOrDefault(x => x.UserId == id).Image;
            ViewBag.Id = id;
            return View(transaction);

        }

        // GET: Admin/UserInformations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/UserInformations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserId,FirstName,LastName,BirthDate,Gender,Image")] UserInformation userInformation)
        {
            if (ModelState.IsValid)
            {
                db.UserInformations.Add(userInformation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(userInformation);
        }

        // GET: Admin/UserInformations/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
               return View("~/Views/Shared/Error.cshtml");
            }
            UserInformation userInformation = db.UserInformations.Find(id);
            if (userInformation == null)
            {
                return HttpNotFound();
            }
            return View(userInformation);
        }

        // POST: Admin/UserInformations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserId,FirstName,LastName,BirthDate,Gender,Image")] UserInformation userInformation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userInformation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userInformation);
        }

        // GET: Admin/UserInformations/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
               return View("~/Views/Shared/Error.cshtml");
            }
            UserInformation userInformation = db.UserInformations.Find(id);
            if (userInformation == null)
            {
                return HttpNotFound();
            }
            return View(userInformation);
        }


        // POST: Admin/UserInformations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            UserInformation userInformation = db.UserInformations.Find(id);
            db.UserInformations.Remove(userInformation);
            AspNetUser aspNetUser = db.AspNetUsers.FirstOrDefault(x => x.Id == id);
            db.AspNetUsers.Remove(aspNetUser);
            var transaction = db.Transactions.Where(x => x.Wallet.UserId == id).ToList();
            if (transaction.Count > 0)
            {
                foreach (var item in transaction)
                {
                    db.Transactions.Remove(item);
                }
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FinanceSystem/Areas/Admin/Views/UserInformations/Create.cshtml
@model FinanceSystem.Models.UserInformation

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserInformation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Gender)
                    @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FinanceSystem/Areas/Admin/Views/UserInformations/Delete.cshtml
@model FinanceSystem.Models.UserInformation

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserInformation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FinanceSystem/Areas/Admin/Views/UserInformations/Details.cshtml
@model IEnumerable<FinanceSystem.Models.Transaction>
@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@{ var format = System.Globalization.CultureInfo.GetCultureInfo("vi-VN");}
<div class="flex-grow bg-white dark:bg-gray-900 overflow-y-auto">
    <div class="sm:px-7 sm:pt-7 px-4 pt-4 flex flex-col w-full border-b border-gray-200 bg-white dark:bg-gray-900 dark:text-white dark:border-gray-800 sticky top-0">

        <div class="flex w-full items-center">
            <div class="flex items-center text-3xl text-gray-900 dark:text-white">
                <img src="@ViewBag.Image" class="w-12 mr-4 rounded-full" alt="profile" />
                <p></p>
            </div>
            <div class="ml-auto sm:flex hidden items-center justify-end">
                <div class="text-right">
                    <div class="text-xs text-gray-400 dark:text-gray-400">Account balance:</div>
                    <div class="text-gray-900 text-lg dark:text-white">
                        $@String.Format(format, "{0:c0}", @ViewBag.Total)
                    </div>
                </div>
                <a href="@Url.Action("Delete", "UserInformations", new {id = ViewBag.Id})">
                    <img src="~/Content/Images/bin.png"  alt="Alternate Text" />
                </a>

            </div>

        </div>
        <div class="flex items-center space-x-3 sm:mt-7 mt-4">
            <a href="#" class="px-3 border-b-2 border-blue-500 text-blue-500 dark:text-white dark:border-white pb-1.5">Transaction</a>
        </div>
    </div>
        <table class="w-full text-left">
            <thead>
                <tr class="text-gray-400">
                    <th class="font-normal px-3 pt-0 pb-3 border-b border-gray-200 dark:border-gray-800">Type</th>
                    <th class="font-normal px-3 pt-0 pb-3 border-b border-gray-200 dark:border-gray-800">Wallet</th>
                    <th class="font-normal px-3 pt-0 pb-3 border-b border-gray-200 dark:border-gray-800 hidden md:table-cell">Note</th>
                    <th class="font-normal px-3 pt-0 pb-3 border-b border-gray-200 dark:border-gray-800">Amount</th>
                    <th class="font-normal px-3 pt-0 pb-3 border-b border-gray-200 dark:border-gray-800 sm:text-gray-400 text-white">Date</th>
                </tr>
            </thead>
            <tbody class="text-gray-600 dark:text-gray-100">
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="sm:p-3 py-2 px-1 border-b border-gray-200 dark:border-gray-800">
                            <div class="flex items-center">
                                <svg viewBox="0 0 24 24" class="w-4 mr-5 text-yellow-500" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                    <circle cx="12" cy="12" r="10"></circle>
                                    <line x1="12" y1="8" x2="12" y2="12"></line>
                                    <line x1="12" y1="16" x2="12.01" y2="16"></line>
                                </svg>
                                @{
                                    if (item.Income == true)
                                    {
                                        <span>Inflow</span>
                                    }
                                    else
                                    {
                                        <span>Outflow</span>
                                    }
                                }

                            </div>
                        </td>
                        <td class="sm:p-3 py-2 px-1 border-b border-gray-200 dark:border-gray-800">
                            <div class="flex items-center">
                               
                                @item.Wallet.WalletName
                            </div>
                        </td>
                        <td class="sm:p-3 py-2 px-1 border-b border-gray-200 dark:border-gray-800 md:table-cell hidden">@item.Note</td>
                        @{
                            if (item.Income == true)
                            {
                                <td class="sm:p-3 py-2 px-1 border-b border-gray-200 dark:border-gray-800 text-green-500">$@String.Format(format, "{0:c0}", item.Amount)</td>
                            }
                            else
                            {
                                <td class="sm:p-3 py-2 px-1 border-b border-gray-200 dark:border-gray-800 text-red-500">$@String.Format(format, "{0:c0}", item.Amount)</td>
                            }
                        }

                        <td class="sm:p-3 py-2 px-1 border-b border-gray-200 dark:border-gray-800">
                            <div class="flex items-center">
                                <div class="sm:flex hidden flex-col">
                                    @item.CreateDate.Value.ToShortDateString()
                                    <div class="text-gray-400 text-xs">@item.CreateDate.Value.ToShortTimeString()</div>
                                </div>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
</div>
}

FinanceSystem/Areas/Admin/Views/UserInformations/Edit.cshtml
@model FinanceSystem.Models.UserInformation

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserInformation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UserId)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Gender)
                    @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FinanceSystem/Areas/Admin/Views/UserInformations/Index.cshtml
@model IEnumerable<FinanceSystem.Models.AspNetUser>
@using FinanceSystem.Models
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@{ var format = System.Globalization.CultureInfo.GetCultureInfo("vi-VN");}
<div class="xl:w-72 w-48 flex-shrink-0 border-r border-gray-200 dark:border-gray-800 h-full overflow-y-auto lg:block hidden p-5">
    <div class="text-xs text-gray-400 tracking-wider">USERS</div>
    <div class="relative mt-2">
        <input type="text" class="pl-8 h-9 bg-transparent border border-gray-300 dark:border-gray-700 dark:text-white w-full rounded-md text-sm" placeholder="Search" />
        <svg viewBox="0 0 24 24" class="w-4 absolute text-gray-400 top-1/2 transform translate-x-0.5 -translate-y-1/2 left-2" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <circle cx="11" cy="11" r="8"></circle>
            <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
        </svg>
    </div>
    <div class="space-y-4 mt-3">
        @foreach (var item in Model)
        {
            <a href="@Url.Action("Details", "UserInformations", new { id = item.Id })">
                <button class="bg-white p-3 w-full flex flex-col rounded-md dark:bg-gray-800 shadow">
                    <div class="flex xl:flex-row flex-col items-center font-medium text-gray-900 dark:text-white pb-2 mb-2 xl:border-b border-gray-200 border-opacity-75 dark:border-gray-700 w-full">

                        <img src="@item.UserInformation.Image" class="w-7 h-7 mr-2 rounded-full" alt="profile" />
                        @item.UserName
                    </div>
                    <div class="flex items-center w-full">
                        @{
                            <div class="text-xs py-1 px-2 leading-none dark:bg-gray-900 bg-blue-100 text-blue-500 rounded-md">Design</div>

                            FinanceSystemDBContext db = new FinanceSystemDBContext();
                            var balance = db.Wallets.Where(x => x.UserId == item.Id).Sum(x => x.AccountBalance);

                            <div class="ml-auto text-xs text-gray-500">@String.Format(format, "{0:c0}", balance)</div>
                            }
                        </div>
                            
                </button>
            </a>

        }

    </div>
</div>
<div class="flex-grow bg-white dark:bg-gray-900 overflow-y-auto">
    <img src="~/Content/Images/cover.png" width="100%" height="100%" alt="Alternate Text" />
</div>