FinanceSystem/Models/TransactionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FinanceSystem.Models
{
    public class TransactionViewModel 
    {
        public IEnumerable<Transaction> Transactions { get; set; }
        public IEnumerable<Category> Categories { get; set; }
    }
}

FinanceSystem/Controllers/TransactionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using System.Web.Util;
using FinanceSystem.Models;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using PagedList;
using PagedList.Mvc;

namespace FinanceSystem.Controllers
{
    [Authorize]
    public class TransactionsController : Controller
    {
        private FinanceSystemDBContext db = new FinanceSystemDBContext();

        // GET: Transactions


        public ActionResult Index()
        {
            string id = User.Identity.GetUserId();
            var transactions = db.Transactions.ToList().Where(x => x.Wallet.UserId == id).ToList();
            var categories = db.Categories.ToList();
            var viewModel = new TransactionViewModel
            {
                Transactions = transactions,
                Categories = categories
            };
            return View(viewModel);
        }

        public PartialViewResult FilterCategory(int? cate)
        {
            string id = User.Identity.GetUserId();
            List<Transaction> list = new List<Transaction>();
            if (cate == null || cate == 0)
            {
                list = db.Transactions.ToList().Where(x => x.Wallet.UserId == id).ToList();
            }
            else
            {
                list = db.Transactions.ToList().Where(x => x.Wallet.UserId == id).ToList().Where(p => p.CategoryId == cate).ToList();

            }

            var totalAmount = list.Sum(x => x.Amount);
            TempData["TotalAmount"] = totalAmount;
            return PartialView(list);
        }


        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return View("~/Views/Shared/Error.cshtml");
        //    }
        //    Transaction transaction = db.Transactions.Find(id);
        //    string userId = User.Identity.GetUserId();
        //    if (transaction.Wallet.UserId != userId)
        //    {
        //        return View("~/Views/Shared/Error.cshtml");
        //    }
        //    if (transaction == null)
        //    {
        //        return View("~/Views/Shared/Error.cshtml");
        //    }
        //    return View(transaction);
        //}

        // GET: Transactions/Create
        public ActionResult Create()
        {
            string id = User.Identity.GetUserId();
            ViewBag.WalletId = new SelectList(db.Wallets.ToList().Where(x => x.UserId == id).ToList(), "WalletId", "WalletName");
            ViewBag.CategoryId = new SelectList(db.Categories.ToList(), "CategoryId", "CategoryName");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TransactionId,WalletId,CategoryId,Amount,CreateDate,Image,Income,Note")] Transaction transaction)
        {
            //string id = User.Identity.GetUserId();
            transaction.ImageFile = Request.Files["ImageFile"];
            if (transaction.ImageFile != null && transaction.ImageFile.ContentLength > 0)
            {
                var fileName = Path.GetFileName(transaction.ImageFile.FileName);
                var filePath = Path.Combine(Server.MapPath("~/Content/Images"), fileName);
                transaction.ImageFile.SaveAs(filePath);
                transaction.Image = "/Content/Images/" + fileName;

            }
            bool? selectedIncome = transaction.Income;
            if (!selectedIncome.Value)
            {
                transaction.Amount *= -1;
            }
            transaction.Amount *= 1;
            if (ModelState.IsValid)
            {
                db.Transactions.Add(transaction);
                Wallet wallet = db.Wallets.FirstOrDefault(x => x.WalletId == transaction.WalletId);
                wallet.AccountBalance += transaction.Amount;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryID", "CategoryName", transaction.CategoryId);
            ViewBag.WalletId = new SelectList(db.Wallets, "WalletId", "UserId", transaction.WalletId);
            return View(transaction);
        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }

            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryID", "CategoryName", transaction.CategoryId);
            ViewBag.WalletId = new SelectList(db.Wallets, "WalletId", "WalletName", transaction.WalletId);
            return PartialView("Edit", transaction);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TransactionId,WalletId,CategoryId,Amount,CreateDate,Income,Image,Note")] Transaction transaction)
        {
            transaction.ImageFile = Request.Files["ImageFile"];
            if (transaction.ImageFile != null && transaction.ImageFile.ContentLength > 0)
            {
                var fileName = Path.GetFileName(transaction.ImageFile.FileName);
                var filePath = Path.Combine(Server.MapPath("~/Content/Images"), fileName);
                transaction.ImageFile.SaveAs(filePath);
                transaction.Image = "/Content/Images/" + fileName;

            }
            bool? selectedIncome = transaction.Income;
            if (!selectedIncome.Value)
            {
                transaction.Amount *= -1;
            }
            transaction.Amount *= 1;
            if (ModelState.IsValid)
            {
                db.Entry(transaction).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryID", "CategoryName", transaction.CategoryId);
            ViewBag.WalletId = new SelectList(db.Wallets, "WalletId", "WalletName", transaction.WalletId);
            return PartialView("Edit", transaction);
        }
      
        public ActionResult Delete(int id)
        {
            try
            {
                Transaction transaction = db.Transactions.Find(id);
                if (transaction == null)
                {
                    return Json(new { success = false, message = "Sản phẩm không tồn tại." });
                }

                db.Transactions.Remove(transaction);
                db.SaveChanges();

                return Json(new { success = true });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = "Lỗi xảy ra khi xóa sản phẩm: " + ex.Message });
            }
        }
        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FinanceSystem/Views/Transactions/Create.cshtml
@model FinanceSystem.Models.Transaction

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
<link href="~/Content/css/Addimage.css" rel="stylesheet" />
<link href="~/Content/css/style.css" rel="stylesheet" />
<h2>Create</h2>


@using (Html.BeginForm("Create", "Transactions", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Transaction</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.WalletId, "Wallet Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("WalletId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.WalletId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "Category Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="datetime-local" name="CreateDate" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Income, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.RadioButtonFor(m => m.Income, "true")
                <label>Inflow</label>
                @Html.RadioButtonFor(m => m.Income, "false")
                <label>Outflow</label>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">



                <body class="body-1">


                    <!-- Upload  -->
                    <div id="file-upload-form" class="uploader">
                        <input id="file-upload" type="file" name="ImageFile" accept="image/*" />

                        <label for="file-upload" id="file-drag">
                            <img id="file-image" src="#" alt="Preview" class="hidden">
                            <div id="start">
                                <i class="fa fa-download" aria-hidden="true"></i>
                                <div>Select a file or drag here</div>
                                <div id="notimage" class="hidden">Please select an image</div>
                                <span id="file-upload-btn" class="btn btn-primary">Select a file</span>
                            </div>
                            <div id="response" class="hidden">
                                <div id="messages"></div>
                                <progress class="progress" id="file-progress" value="0">
                                    <span>0</span>%
                                </progress>
                            </div>
                        </label>
                    </div>
                    <!-- partial -->
                    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js'></script>
                    <script src="~/Content/js/Addimage.js"></script>
                </body>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FinanceSystem/Views/Transactions/Delete.cshtml
@model FinanceSystem.Models.Transaction

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Transaction</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Wallet.WalletName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Wallet.WalletName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FinanceSystem/Views/Transactions/Details.cshtml
@model FinanceSystem.Models.Transaction

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Transaction</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Wallet.WalletName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Wallet.WalletName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TransactionId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FinanceSystem/Views/Transactions/Edit.cshtml
@model FinanceSystem.Models.Transaction

@{
    ViewBag.Title = "Edit";

}



<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
<link rel="stylesheet" href="~/Content/css/style.css">
<link rel="stylesheet" href="~/Content/css/styles.css">
<link href="~/Content/css/menu.css" rel="stylesheet" />
<link href="~/Content/css/edit.css" rel="stylesheet" />
@using (Html.BeginForm("Edit", "Transactions", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Transaction</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TransactionId)

        <div class="form-group">
            @Html.LabelFor(model => model.WalletId, "WalletId", htmlAttributes: new { @class = "control-label col-md-2" } ) 



            <div class="col-md-10">
                @Html.DropDownList("WalletId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.WalletId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateDate, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Income, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.RadioButtonFor(m => m.Income, "true")
                <label>Inflow</label>
                @Html.RadioButtonFor(m => m.Income, "false")
                <label>Outflow</label>
            </div>
        </div>
        <div class="form-group">

            <div class="col-md-10">
                <body class="body-1">
                    <!-- Upload  -->
                    <div id="file-upload-form" class="uploader">
                        <input id="file-upload" type="file" name="ImageFile" accept="image/*" />

                        <label for="file-upload" id="file-drag">
                            <img id="file-image" src="#" alt="Preview" class="hidden">
                            <div id="start">
                                <i class="fa fa-download" aria-hidden="true"></i>
                                <div>Select a file or drag here</div>
                                <div id="notimage" class="hidden">Please select an image</div>
                                <span id="file-upload-btn" class="btn btn-primary">Select a file</span>
                            </div>
                            <div id="response" class="hidden">
                                <div id="messages"></div>
                                <progress class="progress" id="file-progress" value="0">
                                    <span>0</span>%
                                </progress>
                            </div>
                        </label>
                    </div>


                    <!-- partial -->
                    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js'></script>
                    <script src="~/Content/js/Addimage.js"></script>
                </body>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2", style = "right: 372px;   top: 153pt;" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control", style = "margin: 29px" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<style>
</style>
<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "my-lin" })
    <style>
        .my-lin {
            text-decoration:none;
            position: relative;
            top: 282px;
            color:#173599
        }
    </style>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FinanceSystem/Views/Transactions/Index.cshtml
@model FinanceSystem.Models.TransactionViewModel



<link href="~/Content/css/Addimage.css" rel="stylesheet" />
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/css/style.css" rel="stylesheet" />
<link href="~/Content/css/menu.css" rel="stylesheet" />
<div class="app-content-header">
    <h1 class="app-content-headerText">Transaction</h1>
    <button class="mode-switch" title="Switch Theme">
        <svg class="moon" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" width="24" height="24" viewBox="0 0 24 24">
            <defs></defs>
            <path d="M21 12.79A9 9 0 1111.21 3 7 7 0 0021 12.79z"></path>
        </svg>
    </button>
    <a href="@Url.Action("Create", "Transactions")"> <button class="app-content-headerButton">Add Transaction</button></a>

</div>
<div class="app-content-actions">
    <input class="search-bar" placeholder="Search..." type="text">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $(".search-bar").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $(".products-row").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>

    <div class="app-content-actions-wrapper">
        <div class="filter-button-wrapper">
            <button class="action-button filter jsFilter"><span>Filter</span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-filter"><polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3" /></svg></button>
            <div class="filter-menu">
                <label>Category</label>
                <select id="categoryFilter">
                    <option value="0">All Categories</option>
                    @foreach (var item in Model.Categories)
                    {
                        <option value="@item.CategoryID">@item.CategoryName</option>
                    }
                </select>
                <label>Status</label>
                <select>
                    <option>All Status</option>
                    <option>Active</option>
                    <option>Disabled</option>
                </select>
                <div class="filter-menu-buttons">
                    <button class="filter-button reset">
                        Reset
                    </button>
                    <button class="filter-button apply" id="filterButton">
                        Apply
                    </button>

                </div>
            </div>
        </div>
        <button class="action-button list active" title="List View">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-list"><line x1="8" y1="6" x2="21" y2="6" /><line x1="8" y1="12" x2="21" y2="12" /><line x1="8" y1="18" x2="21" y2="18" /><line x1="3" y1="6" x2="3.01" y2="6" /><line x1="3" y1="12" x2="3.01" y2="12" /><line x1="3" y1="18" x2="3.01" y2="18" /></svg>
        </button>
        <button class="action-button grid" title="Grid View">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-grid"><rect x="3" y="3" width="7" height="7" /><rect x="14" y="3" width="7" height="7" /><rect x="14" y="14" width="7" height="7" /><rect x="3" y="14" width="7" height="7" /></svg>
        </button>
    </div>
</div>
@{ @Html.Action("FilterCategory") }
<script src="~/Content/js/menu.js"></script>

<script>
    $(document).ready(function () {
        $('#filterButton').click(function () {
            var category = $('#categoryFilter').find(":selected").val();

            $('.loadNe').load('@Url.Action("FilterCategory", "Transactions")' + '?cate=' + category);

        });
    });
</script>